name: Publish Durable Task Scheduler to PyPI

on:
  push:
    tags:
      - 'v*'  # Only run for tags starting with "v"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV  # Extract version from the tag

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # Adjust Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package from directory durabletask-azuremanaged
        run: |
          cd durabletask-azuremanaged 
          python -m build 

      - name: Check package
        run: |
          cd durabletask-azuremanaged 
          twine check dist/* 

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Store your PyPI API token in GitHub Secrets
        run: |
          cd durabletask-azuremanaged 
          twine upload dist/* 
